table DIM_Categorie
	lineageTag: 875486ee-1b6f-4062-b099-6f573a4c84fa

	column ID_Categorie
		dataType: int64
		formatString: 0
		lineageTag: a9899ba3-8e5b-48a3-912a-0a805022669b
		summarizeBy: none
		sourceColumn: ID_Categorie

		annotation SummarizationSetBy = Automatic

	column Nom_Categorie
		dataType: string
		lineageTag: b0259064-eec8-49c6-9c2f-8e159d231faa
		summarizeBy: none
		sourceColumn: Nom_Categorie

		annotation SummarizationSetBy = Automatic

	column Type_Flux
		dataType: string
		lineageTag: 8ef7fddb-7cd2-4d40-9f01-47947d678c75
		summarizeBy: none
		sourceColumn: Type_Flux

		annotation SummarizationSetBy = Automatic

	partition DIM_Categorie = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\KIMYAÉDITION\source\repos\GFMP\GFMP_V1.0.xlsm"), null, true),
				    DIM_Categorie_Sheet = Source{[Item="DIM_Categorie",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DIM_Categorie_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID_Categorie", Int64.Type}, {"Nom_Categorie", type text}, {"Type_Flux", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

