table T_DIM_Tiers
	lineageTag: a01387ca-f070-4d14-b88e-7ad8bace45ae

	column ID_Tiers
		dataType: int64
		formatString: 0
		lineageTag: 41115c5e-3b92-44c2-abbc-d830fbf205d8
		summarizeBy: none
		sourceColumn: ID_Tiers

		annotation SummarizationSetBy = Automatic

	column Nom_Tiers
		dataType: string
		lineageTag: 1a16d593-8f2f-4686-b793-c9c1d8842b28
		summarizeBy: none
		sourceColumn: Nom_Tiers

		annotation SummarizationSetBy = Automatic

	column Type_Tiers
		dataType: string
		lineageTag: 5fdbddfc-bde6-43b0-b6a7-a712f7ebf978
		summarizeBy: none
		sourceColumn: Type_Tiers

		annotation SummarizationSetBy = Automatic

	partition T_DIM_Tiers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\KIMYAÉDITION\source\repos\GFMP\GFMP_V1.0.xlsm"), null, true),
				    T_DIM_Tiers_Table = Source{[Item="T_DIM_Tiers",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(T_DIM_Tiers_Table,{{"ID_Tiers", Int64.Type}, {"Nom_Tiers", type text}, {"Type_Tiers", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

