table T_DIM_Categorie
	lineageTag: 3ffd4144-90b7-49ae-96b3-873211dc813f

	column ID_Categorie
		dataType: int64
		formatString: 0
		lineageTag: eba7b889-426c-40f4-b012-a2ab5c76807d
		summarizeBy: none
		sourceColumn: ID_Categorie

		annotation SummarizationSetBy = Automatic

	column Nom_Categorie
		dataType: string
		lineageTag: 5d9a4815-28ce-4769-82be-9ab05364c613
		summarizeBy: none
		sourceColumn: Nom_Categorie

		annotation SummarizationSetBy = Automatic

	column Type_Flux
		dataType: string
		lineageTag: 18beaa3e-576c-4c2d-9310-faa909b003a0
		summarizeBy: none
		sourceColumn: Type_Flux

		annotation SummarizationSetBy = Automatic

	partition T_DIM_Categorie = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\KIMYAÉDITION\source\repos\GFMP\GFMP_V1.0.xlsm"), null, true),
				    T_DIM_Categorie_Table = Source{[Item="T_DIM_Categorie",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(T_DIM_Categorie_Table,{{"ID_Categorie", Int64.Type}, {"Nom_Categorie", type text}, {"Type_Flux", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

