table T_FACT_Budget
	lineageTag: 87baee70-56e9-4029-8b6b-31afd8a016d5

	column ID_Budget
		dataType: int64
		formatString: 0
		lineageTag: 3cc722d9-4bac-4b9f-9c7d-e87196e159c7
		summarizeBy: sum
		sourceColumn: ID_Budget

		annotation SummarizationSetBy = Automatic

	column Mois_Annee
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6955ea40-3e69-4e0b-9ce7-29c733f65887
		summarizeBy: none
		sourceColumn: Mois_Annee

		variation Variation
			isDefault
			relationship: 3f3f7feb-fdd6-4668-b33b-38cae1e87025
			defaultHierarchy: LocalDateTable_659b3c57-e23c-4c3a-aaa6-479f29ede4d1.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ID_Categorie
		dataType: int64
		formatString: 0
		lineageTag: 1cae2405-3dd0-4d40-9f1a-e007eaeb82e2
		summarizeBy: none
		sourceColumn: ID_Categorie

		annotation SummarizationSetBy = Automatic

	column Montant_Alloue
		dataType: int64
		formatString: 0
		lineageTag: 708ebbf9-b8c8-485d-a8a9-b5d2cf96f2d5
		summarizeBy: sum
		sourceColumn: Montant_Alloue

		annotation SummarizationSetBy = Automatic

	column SYS_User
		dataType: string
		lineageTag: 3284356f-c1ad-4feb-9b39-41e9169b9f06
		summarizeBy: none
		sourceColumn: SYS_User

		annotation SummarizationSetBy = Automatic

	column SYS_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d938463-1799-453e-9427-ad03b5f87d92
		summarizeBy: none
		sourceColumn: SYS_Date

		variation Variation
			isDefault
			relationship: 0ba05729-da16-4bc2-9956-90278e619e49
			defaultHierarchy: LocalDateTable_3efb3915-3c7a-4cb0-a653-04774ad7886e.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	partition T_FACT_Budget = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\KIMYAÉDITION\source\repos\GFMP\GFMP_V1.0.xlsm"), null, true),
				    T_FACT_Budget_Table = Source{[Item="T_FACT_Budget",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(T_FACT_Budget_Table,{{"ID_Budget", Int64.Type}, {"Mois_Annee", type date}, {"ID_Categorie", Int64.Type}, {"Montant_Alloue", Int64.Type}, {"SYS_User", type text}, {"SYS_Date", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

